"""create traders table

Revision ID: 0388d30f07ae
Revises: 
Create Date: 2025-12-05 19:05:05.632894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0388d30f07ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('primary_sport', sa.String(length=50), nullable=True),
    sa.Column('secondary_sport', sa.String(length=50), nullable=True),
    sa.Column('required_days_per_week', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traders')
    # ### end Alembic commands ###

