"""add_location_and_sport_config_tables

Revision ID: 1aabfac9558b
Revises: 45aeaec9586d
Create Date: 2025-12-06 23:06:42.829946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aabfac9558b'
down_revision = '45aeaec9586d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # Note: SQLite doesn't support ALTER COLUMN for nullability changes
    # Alias nullability is enforced at the application layer
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER COLUMN for nullability changes
    op.drop_table('sports')
    op.drop_table('locations')
    # ### end Alembic commands ###

