"""add trader requests table

Revision ID: 45aeaec9586d
Revises: f0298b67d845
Create Date: 2025-12-06 20:38:32.522840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45aeaec9586d'
down_revision = 'f0298b67d845'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trader_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('request_kind', sa.String(length=50), nullable=False),
    sa.Column('effect_type', sa.String(length=50), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.String(length=20), nullable=True),
    sa.Column('sport_code', sa.String(length=20), nullable=True),
    sa.Column('destination', sa.String(length=10), nullable=True),
    sa.Column('leave_type', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trader_requests_id'), 'trader_requests', ['id'], unique=False)
    op.create_index(op.f('ix_trader_requests_trader_id'), 'trader_requests', ['trader_id'], unique=False)
    # Note: SQLite doesn't support ALTER COLUMN, so we skip the alias column change
    # The alias column is already nullable in the database
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER COLUMN, so we skip the alias column change
    op.drop_index(op.f('ix_trader_requests_trader_id'), table_name='trader_requests')
    op.drop_index(op.f('ix_trader_requests_id'), table_name='trader_requests')
    op.drop_table('trader_requests')
    # ### end Alembic commands ###

