"""align traders table with canonical trader base

Revision ID: 98a838adc56a
Revises: 0388d30f07ae
Create Date: 2025-12-05 19:40:19.407667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a838adc56a'
down_revision = '0388d30f07ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Columns already exist in database, commented out to avoid duplicate column error
    # op.add_column('traders', sa.Column('manager', sa.String(length=100), nullable=True))
    # op.add_column('traders', sa.Column('hours_per_week', sa.Integer(), nullable=True))
    # SQLite doesn't support ALTER COLUMN, commented out to avoid syntax error
    # op.alter_column('traders', 'alias',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, commented out to avoid syntax error
    # op.alter_column('traders', 'alias',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=False)
    # Columns were not added in upgrade, so don't drop them in downgrade
    # op.drop_column('traders', 'hours_per_week')
    # op.drop_column('traders', 'manager')
    # ### end Alembic commands ###
    pass

