"""add weekly patterns and trader preferences

Revision ID: f0298b67d845
Revises: 98a838adc56a
Create Date: 2025-12-05 23:12:17.834201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0298b67d845'
down_revision = '98a838adc56a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trader_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_id', 'category', 'key', name='uq_trader_preference_unique')
    )
    op.create_index(op.f('ix_trader_preferences_id'), 'trader_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_trader_preferences_trader_id'), 'trader_preferences', ['trader_id'], unique=False)
    op.create_table('trader_weekly_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('shift_type', sa.String(length=10), nullable=False),
    sa.Column('hard_block', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_id', 'day_of_week', 'shift_type', name='uq_trader_weekly_pattern_cell')
    )
    op.create_index(op.f('ix_trader_weekly_patterns_id'), 'trader_weekly_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_trader_weekly_patterns_trader_id'), 'trader_weekly_patterns', ['trader_id'], unique=False)
    # SQLite doesn't support ALTER COLUMN, commented out to avoid syntax error
    # op.alter_column('traders', 'alias',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, commented out to avoid syntax error
    # op.alter_column('traders', 'alias',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=False)
    op.drop_index(op.f('ix_trader_weekly_patterns_trader_id'), table_name='trader_weekly_patterns')
    op.drop_index(op.f('ix_trader_weekly_patterns_id'), table_name='trader_weekly_patterns')
    op.drop_table('trader_weekly_patterns')
    op.drop_index(op.f('ix_trader_preferences_trader_id'), table_name='trader_preferences')
    op.drop_index(op.f('ix_trader_preferences_id'), table_name='trader_preferences')
    op.drop_table('trader_preferences')
    # ### end Alembic commands ###

